package com.mrbt.yeston.web.model;

import java.io.Serializable;
import java.util.Date;

public class ScheduleLog implements Serializable {
    /**
     * 
     * 表字段 : schedule_log.id
     */
    private Integer id;

    /**
     * schedule_job id
     * 表字段 : schedule_log.job_id
     */
    private Integer jobId;

    /**
     * 执行时间
     * 表字段 : schedule_log.execute_time
     */
    private Date executeTime;

    /**
     * 执行记录描述
     * 表字段 : schedule_log.description
     */
    private String description;

    /**
     * 错误日志
     * 表字段 : schedule_log.error_log
     */
    private String errorLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table schedule_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:schedule_log.id
     *
     * @return schedule_log.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:schedule_log.id
     *
     * @param id the value for schedule_log.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 schedule_job id 字段:schedule_log.job_id
     *
     * @return schedule_log.job_id, schedule_job id
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * 设置 schedule_job id 字段:schedule_log.job_id
     *
     * @param jobId the value for schedule_log.job_id, schedule_job id
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * 获取 执行时间 字段:schedule_log.execute_time
     *
     * @return schedule_log.execute_time, 执行时间
     */
    public Date getExecuteTime() {
        return executeTime;
    }

    /**
     * 设置 执行时间 字段:schedule_log.execute_time
     *
     * @param executeTime the value for schedule_log.execute_time, 执行时间
     */
    public void setExecuteTime(Date executeTime) {
        this.executeTime = executeTime;
    }

    /**
     * 获取 执行记录描述 字段:schedule_log.description
     *
     * @return schedule_log.description, 执行记录描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置 执行记录描述 字段:schedule_log.description
     *
     * @param description the value for schedule_log.description, 执行记录描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取 错误日志 字段:schedule_log.error_log
     *
     * @return schedule_log.error_log, 错误日志
     */
    public String getErrorLog() {
        return errorLog;
    }

    /**
     * 设置 错误日志 字段:schedule_log.error_log
     *
     * @param errorLog the value for schedule_log.error_log, 错误日志
     */
    public void setErrorLog(String errorLog) {
        this.errorLog = errorLog == null ? null : errorLog.trim();
    }

    /**
     * ,schedule_log
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jobId=").append(jobId);
        sb.append(", executeTime=").append(executeTime);
        sb.append(", description=").append(description);
        sb.append(", errorLog=").append(errorLog);
        sb.append("]");
        return sb.toString();
    }
}