package com.mrbt.yeston.rong360.tianji.mongo;

import org.springframework.data.mongodb.core.mapping.Document;

/** 
 * @author  suyibo 
 * @date 创建时间：2018年2月24日
 */
@Document(collection = "tianji_pengyuan_mobilecheck_mongo")
public class PengyuanMobilecheck {
	/**
	 * 数据id
	 */
	private String id;
	/**
	 * 接口名
	 */
	private String method;
	/**
	 * 接口名
	 */
	private String methodName;
	/**
	 * 用户姓名
	 */
	private String name;
	/**
	 * 身份证号
	 */
	private String idNumber;
	/**
	 * 电话
	 */
	private String phone;
	/**
	 * S一致，F不一致，U未知，数据源没有覆盖到
	 */
	private String checkStatus;
	/**
	 * 验证消息
	 */
	private String message;
	/**
	 * 姓名查询结果
	 */
	private String nameCheckResult;
	/**
	 * 身份证查询结果
	 */
	private String documentNoCheckResult;
	/**
	 * 手机号查询结果
	 */
	private String phoneCheckResult;
	/**
	 * 地区信息
	 */
	private String areaInfo;
	/**
	 * 运营商 1：中国电信 2：中国移动 .3:中国联通
	 */
	private String operator;
	/**
	 * 创建时间
	 */
	private String createDate;
	/**
	 * DataInfo数据id
	 */
	private String dataInfoId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table syn_user_data
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getMethodName() {
		return methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCheckStatus() {
		return checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getNameCheckResult() {
		return nameCheckResult;
	}

	public void setNameCheckResult(String nameCheckResult) {
		this.nameCheckResult = nameCheckResult;
	}

	public String getDocumentNoCheckResult() {
		return documentNoCheckResult;
	}

	public void setDocumentNoCheckResult(String documentNoCheckResult) {
		this.documentNoCheckResult = documentNoCheckResult;
	}

	public String getPhoneCheckResult() {
		return phoneCheckResult;
	}

	public void setPhoneCheckResult(String phoneCheckResult) {
		this.phoneCheckResult = phoneCheckResult;
	}

	public String getAreaInfo() {
		return areaInfo;
	}

	public void setAreaInfo(String areaInfo) {
		this.areaInfo = areaInfo;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getDataInfoId() {
		return dataInfoId;
	}

	public void setDataInfoId(String dataInfoId) {
		this.dataInfoId = dataInfoId;
	}

}
